name: Deploy

# Listen for push and pull_request events on the master branch.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i pnpm -g
        # 4️⃣ 允许所有构建脚本
      - name: Approve build scripts
        run: |
          pnpm approve-builds --all
          echo "PNPM_ENABLE_SCRIPTS=true" >> $GITHUB_ENV

        # 5️⃣ 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

        # 6️⃣ 强制构建 sharp（如仍有问题）
      - name: Force rebuild sharp
        run: pnpm rebuild sharp

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 。/dist
